index:
    path: /
    controller: App\Controller\DefaultController::index


activity_log_new:
    path: /activitylog/new
    controller: App\Controller\ActivityLogController::new

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
