index:
    path: /
    controller: App\Controller\DefaultController::index


activity_log_new:
    path: /authed/activitylog/new
    controller: App\Controller\ActivityLogController::new

project_new:
    path: /authed/project/new
    controller: App\Controller\ProjectController::new

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
